// <auto-generated>
//     This file was generated by valuetask2task.sh.
//     Do not modify manually. Changes may be overwritten.
// </auto-generated>

#nullable enable

namespace UnambitiousFx.Functional.Tasks;

public static partial class MaybeExtensions
{
    /// <summary>
    ///     Asynchronously binds a function to a Task-wrapped Maybe value, transforming the value if present.
    /// </summary>
    /// <typeparam name="TIn">The type of the input value.</typeparam>
    /// <typeparam name="TOut">The type of the output value.</typeparam>
    /// <param name="option">The Task-wrapped Maybe value to bind.</param>
    /// <param name="bind">The function to apply to the value if present.</param>
    /// <returns>A Task containing the transformed Maybe value if present, otherwise None.</returns>
    public static Task<Maybe<TOut>> BindAsync<TIn, TOut>(this Task<Maybe<TIn>> option,
        Func<TIn, Maybe<TOut>> bind)
        where TIn : notnull
        where TOut : notnull
    {
        return option.MatchAsync(bind, Maybe.None<TOut>);
    }
}
