// <auto-generated>
//     This file was generated by valuetask2task.sh.
//     Do not modify manually. Changes may be overwritten.
// </auto-generated>

#nullable enable

namespace UnambitiousFx.Functional.Tasks;

/// <summary>
///     Provides extension methods for Task-wrapped Result instances.
/// </summary>
public static partial class ResultExtensions;
