// <auto-generated>
//     This file was generated by valuetask2task.sh.
//     Do not modify manually. Changes may be overwritten.
// </auto-generated>

#nullable enable

using UnambitiousFx.Functional.Errors;

namespace UnambitiousFx.Functional.Tasks;

public static partial class ResultExtensions
{
    /// <summary>
    ///     Ensures all items in a Task-wrapped collection result satisfy the given predicate.
    /// </summary>
    /// <typeparam name="TCollection">The collection type implementing IEnumerable&lt;TItem&gt;.</typeparam>
    /// <typeparam name="TItem">The item type in the collection.</typeparam>
    /// <param name="resultTask">The Task-wrapped result instance.</param>
    /// <param name="predicate">The predicate that all items must satisfy.</param>
    /// <param name="message">Optional validation error message.</param>
    /// <param name="field">Optional field name for the error message.</param>
    /// <returns>The original result if all items satisfy the predicate; otherwise a failure with ValidationError.</returns>
    public static async Task<Result<TCollection>> EnsureAll<TCollection, TItem>(
        this Task<Result<TCollection>> resultTask, Func<TItem, bool> predicate, string? message = null,
        string? field = null)
        where TCollection : IEnumerable<TItem>
    {
        var result = await resultTask;
        return result.EnsureAll<TCollection, TItem>(predicate, message, field);
    }

    /// <summary>
    ///     Ensures all items in a Task-wrapped collection result satisfy the given predicate with custom error factory.
    /// </summary>
    /// <typeparam name="TCollection">The collection type implementing IEnumerable&lt;TItem&gt;.</typeparam>
    /// <typeparam name="TItem">The item type in the collection.</typeparam>
    /// <param name="resultTask">The Task-wrapped result instance.</param>
    /// <param name="predicate">The predicate that all items must satisfy.</param>
    /// <param name="errorFactory">Factory function to create an error when validation fails.</param>
    /// <returns>The original result if all items satisfy the predicate; otherwise a failure with the error from the factory.</returns>
    public static async Task<Result<TCollection>> EnsureAll<TCollection, TItem>(
        this Task<Result<TCollection>> resultTask, Func<TItem, bool> predicate,
        Func<TCollection, Error> errorFactory)
        where TCollection : IEnumerable<TItem>
    {
        var result = await resultTask;
        return result.EnsureAll<TCollection, TItem>(predicate, errorFactory);
    }
}
