// <auto-generated>
//     This file was generated by valuetask2task.sh.
//     Do not modify manually. Changes may be overwritten.
// </auto-generated>

#nullable enable

namespace UnambitiousFx.Functional.Tasks;

public static partial class ResultExtensions
{
    /// <summary>
    ///     Async ToNullable returning nullable value(s) when success, null when failure.
    /// </summary>
    public static async Task<TValue1?> ToNullableAsync<TValue1>(this Task<Result<TValue1>> awaitable)
        where TValue1 : notnull
    {
        var result = await awaitable.ConfigureAwait(false);
        return result.ToNullable();
    }
}