// <auto-generated>
//     This file was generated by valuetask2task.sh.
//     Do not modify manually. Changes may be overwritten.
// </auto-generated>

#nullable enable

using UnambitiousFx.Functional.Errors;

namespace UnambitiousFx.Functional.Tasks;

public static partial class ResultExtensions
{
    /// <summary>
    ///     Async Match for pattern matching on Result, executing success or failure handler.
    /// </summary>
    public static async Task<TOut> MatchAsync<TOut, TValue1>(this Task<Result<TValue1>> awaitableResult,
        Func<TValue1, Task<TOut>> success, Func<Error, Task<TOut>> failure)
        where TOut : notnull where TValue1 : notnull
    {
        var result = await awaitableResult.ConfigureAwait(false);
        return await result.Match(success, failure);
    }

    /// <summary>
    ///     Async Match for pattern matching on Result, executing success or failure handler.
    /// </summary>
    public static async Task MatchAsync<TValue1>(this Task<Result<TValue1>> awaitableResult,
        Func<TValue1, Task> success, Func<Error, Task> failure) where TValue1 : notnull
    {
        var result = await awaitableResult.ConfigureAwait(false);
        await result.Match(success, failure);
    }
}