version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
      benchmarkdotnet:
        patterns:
          - "BenchmarkDotNet*"
      testing:
        patterns:
          - "xunit*"
          - "NSubstitute*"
          - "coverlet*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
