// <auto-generated>
//     This file was generated by valuetask2task.sh.
//     Do not modify manually. Changes may be overwritten.
// </auto-generated>

#nullable enable

using UnambitiousFx.Functional.Tasks;

namespace UnambitiousFx.Functional.Tests.Tasks;

public sealed class MaybeExtensionsMatchTests
{
    [Fact]
    public async Task MatchAsync_WithSome_ReturnsSomeResult()
    {
        // Arrange (Given)
        var maybeTask = Task.FromResult(Maybe.Some(42));

        // Act (When)
        var result = await maybeTask.MatchAsync(
            some: v => v * 2,
            none: () => 0);

        // Assert (Then)
        Assert.Equal(84, result);
    }

    [Fact]
    public async Task MatchAsync_WithNone_ReturnsNoneResult()
    {
        // Arrange (Given)
        var maybeTask = Task.FromResult(Maybe.None<int>());

        // Act (When)
        var result = await maybeTask.MatchAsync(
            some: v => v * 2,
            none: () => -1);

        // Assert (Then)
        Assert.Equal(-1, result);
    }
}
