// <auto-generated>
//     This file was generated by valuetask2task.sh.
//     Do not modify manually. Changes may be overwritten.
// </auto-generated>

#nullable enable

using UnambitiousFx.Functional.Tasks;

namespace UnambitiousFx.Functional.Tests.Tasks;

public sealed class MaybeExtensionsMatchTests
{
    [Fact]
    public async Task MatchAsync_WithSome_ReturnsSomeResult()
    {
        // Arrange (Given)
        var maybeTask = Task.FromResult(Maybe.Some(42));

        // Act (When)
        var result = await maybeTask.MatchAsync(
            some: v => v * 2,
            none: () => 0);

        // Assert (Then)
        Assert.Equal(84, result);
    }

    [Fact]
    public async Task MatchAsync_WithNone_ReturnsNoneResult()
    {
        // Arrange (Given)
        var maybeTask = Task.FromResult(Maybe.None<int>());

        // Act (When)
        var result = await maybeTask.MatchAsync(
            some: v => v * 2,
            none: () => -1);

        // Assert (Then)
        Assert.Equal(-1, result);
    }

    [Fact]
    public async Task MatchAsync_WithAsyncHandlers_WithSome_ReturnsSomeResult()
    {
        // Arrange (Given)
        var maybeTask = Task.FromResult(Maybe.Some(42));

        // Act (When)
        var result = await maybeTask.MatchAsync(
            some: v => Task.FromResult(v * 2),
            none: () => Task.FromResult(0));

        // Assert (Then)
        Assert.Equal(84, result);
    }

    [Fact]
    public async Task MatchAsync_WithAsyncHandlers_WithNone_ReturnsNoneResult()
    {
        // Arrange (Given)
        var maybeTask = Task.FromResult(Maybe.None<int>());

        // Act (When)
        var result = await maybeTask.MatchAsync(
            some: v => Task.FromResult(v * 2),
            none: () => Task.FromResult(-1));

        // Assert (Then)
        Assert.Equal(-1, result);
    }

    [Fact]
    public async Task MatchAsync_WithAsyncHandlers_WithSome_ExecutesAsyncOperation()
    {
        // Arrange (Given)
        var maybeTask = Task.FromResult(Maybe.Some("test"));
        var executed = false;

        // Act (When)
        var result = await maybeTask.MatchAsync(
            some: async v =>
            {
                await Task.Delay(1);
                executed = true;
                return v.ToUpper();
            },
            none: () => Task.FromResult(string.Empty));

        // Assert (Then)
        Assert.Equal("TEST", result);
        Assert.True(executed);
    }

    [Fact]
    public async Task MatchAsync_WithAsyncHandlers_WithNone_ExecutesAsyncOperation()
    {
        // Arrange (Given)
        var maybeTask = Task.FromResult(Maybe.None<string>());
        var executed = false;

        // Act (When)
        var result = await maybeTask.MatchAsync(
            some: v => Task.FromResult(v.ToUpper()),
            none: async () =>
            {
                await Task.Delay(1);
                executed = true;
                return "default";
            });

        // Assert (Then)
        Assert.Equal("default", result);
        Assert.True(executed);
    }
}
