// <auto-generated>
//     This file was generated by valuetask2task.sh.
//     Do not modify manually. Changes may be overwritten.
// </auto-generated>

#nullable enable

using UnambitiousFx.Functional.Tasks;
using UnambitiousFx.Functional.xunit;

namespace UnambitiousFx.Functional.Tests.Tasks;

/// <summary>
///     Tests for Then, Bind, Ensure, and TryAsync awaitable wrapper extensions using Task.
/// </summary>
public sealed partial class ResultExtensions
{
    [Fact]
    public async Task EnsureInRange_WithAwaitableSuccess_InRange_RemainsSuccess()
    {
        // Arrange (Given)
        var awaitableResult = Task.FromResult(Result.Success(5));

        // Act (When)
        var ensured = await awaitableResult.EnsureInRange(1, 10);

        // Assert (Then)
        ensured.ShouldBe().Success();
    }

    [Fact]
    public async Task EnsureInRange_WithAwaitableSuccess_OutOfRange_BecomesFailure()
    {
        // Arrange (Given)
        var awaitableResult = Task.FromResult(Result.Success(15));

        // Act (When)
        var ensured = await awaitableResult.EnsureInRange(1, 10);

        // Assert (Then)
        ensured.ShouldBe().Failure();
    }

    [Fact]
    public async Task EnsureGreaterThan_WithAwaitableSuccess_IsGreater_RemainsSuccess()
    {
        // Arrange (Given)
        var awaitableResult = Task.FromResult(Result.Success(10));

        // Act (When)
        var ensured = await awaitableResult.EnsureGreaterThan(5);

        // Assert (Then)
        ensured.ShouldBe().Success();
    }

    [Fact]
    public async Task EnsureGreaterThan_WithAwaitableSuccess_IsNotGreater_BecomesFailure()
    {
        // Arrange (Given)
        var awaitableResult = Task.FromResult(Result.Success(3));

        // Act (When)
        var ensured = await awaitableResult.EnsureGreaterThan(5);

        // Assert (Then)
        ensured.ShouldBe().Failure();
    }

    [Fact]
    public async Task EnsureLessThan_WithAwaitableSuccess_IsLess_RemainsSuccess()
    {
        // Arrange (Given)
        var awaitableResult = Task.FromResult(Result.Success(3));

        // Act (When)
        var ensured = await awaitableResult.EnsureLessThan(5);

        // Assert (Then)
        ensured.ShouldBe().Success();
    }

    [Fact]
    public async Task EnsureLessThan_WithAwaitableSuccess_IsNotLess_BecomesFailure()
    {
        // Arrange (Given)
        var awaitableResult = Task.FromResult(Result.Success(10));

        // Act (When)
        var ensured = await awaitableResult.EnsureLessThan(5);

        // Assert (Then)
        ensured.ShouldBe().Failure();
    }
}
