// <auto-generated>
//     This file was generated by valuetask2task.sh.
//     Do not modify manually. Changes may be overwritten.
// </auto-generated>

#nullable enable

using UnambitiousFx.Functional.Errors;
using UnambitiousFx.Functional.Tasks;

namespace UnambitiousFx.Functional.Tests.Tasks;

/// <summary>
///     Tests for MapError, Match, MatchError, and Recover async extensions using Task.
/// </summary>
public sealed partial class ResultExtensions
{
    [Fact]
    public async Task MatchErrorAsync_NonGenericResult_WithMatchingError_ExecutesErrorFunc()
    {
        // Arrange (Given)
        var result = Result.Failure(new ExceptionalError(new InvalidOperationException("Test")));

        // Act (When)
        var output = await result.MatchErrorAsync<ExceptionalError, string>(
            async error =>
            {
                await Task.CompletedTask;
                return "Matched";
            },
            async () =>
            {
                await Task.CompletedTask;
                return "Not matched";
            });

        // Assert (Then)
        Assert.Equal("Matched", output);
    }

    [Fact]
    public async Task MatchErrorAsync_NonGenericResult_WithAwaitableMatchingError_ExecutesErrorFunc()
    {
        // Arrange (Given)
        var awaitableResult =
            Task.FromResult(Result.Failure(new ExceptionalError(new InvalidOperationException("Test"))));

        // Act (When)
        var output = await awaitableResult.MatchErrorAsync<ExceptionalError, string>(
            async error =>
            {
                await Task.CompletedTask;
                return "Matched";
            },
            async () =>
            {
                await Task.CompletedTask;
                return "Not matched";
            });

        // Assert (Then)
        Assert.Equal("Matched", output);
    }

    [Fact]
    public async Task MatchErrorAsync_GenericResult_WithMatchingError_ExecutesErrorFunc()
    {
        // Arrange (Given)
        var result = Result.Failure<int>(new ExceptionalError(new InvalidOperationException("Test")));

        // Act (When)
        var output = await result.MatchErrorAsync<ExceptionalError, int, string>(
            async error =>
            {
                await Task.CompletedTask;
                return "Matched";
            },
            async () =>
            {
                await Task.CompletedTask;
                return "Not matched";
            });

        // Assert (Then)
        Assert.Equal("Matched", output);
    }

    [Fact]
    public async Task MatchErrorAsync_GenericResult_WithAwaitableSuccess_ExecutesOtherwiseFunc()
    {
        // Arrange (Given)
        var awaitableResult = Task.FromResult(Result.Success(42));

        // Act (When)
        var output = await awaitableResult.MatchErrorAsync<ExceptionalError, int, string>(
            async error =>
            {
                await Task.CompletedTask;
                return "Matched";
            },
            async () =>
            {
                await Task.CompletedTask;
                return "Not matched";
            });

        // Assert (Then)
        Assert.Equal("Not matched", output);
    }
}
