// <auto-generated>
//     This file was generated by valuetask2task.sh.
//     Do not modify manually. Changes may be overwritten.
// </auto-generated>

#nullable enable

using Microsoft.AspNetCore.Mvc;
using UnambitiousFx.Functional.AspNetCore.Mappers;

namespace UnambitiousFx.Functional.AspNetCore.Mvc.Tasks;

/// <summary>
///     Provides extension methods for converting <see cref="Result" /> and <see cref="Task" /> of
///     <see cref="Result" />
///     into HTTP-compatible results using <see cref="Microsoft.AspNetCore.Http.IResult" />.
/// </summary>
public static class ResultHttpExtensions
{
    /// <summary>
    /// Provides extension methods for converting <see cref="Task{TResult}" /> of <see cref="Result" />
    /// into HTTP-compatible results using <see cref="Microsoft.AspNetCore.Mvc.IActionResult" />.
    /// </summary>
    extension(Task<Result> awaitableResult)
    {
        /// <summary>
        ///     Converts a Result to an IResult for use in minimal API endpoints.
        ///     Maps success to the provided success result and failure to an appropriate status code or response body.
        /// </summary>
        /// <param name="httpMapper">A function mapping a successful Result to an IActionResult.</param>
        /// <param name="errorMapper">
        ///     Optional custom mapper for handling error cases. Uses a default implementation if not
        ///     supplied.
        /// </param>
        /// <returns>An IActionResult representing either success or failure.</returns>
        public async Task<IActionResult> ToActionResultAsync(Func<IActionResult> httpMapper,
            IErrorHttpMapper? errorMapper = null)
        {
            var result = await awaitableResult;
            return result.ToActionResult(httpMapper, errorMapper);
        }

        /// <summary>
        ///     Converts a Result to an IResult for minimal API endpoints.
        ///     Success returns 200 OK, failure maps error to appropriate status code.
        /// </summary>
        /// <param name="errorMapper">Optional custom error mapper. Uses default if not provided.</param>
        /// <returns>An IResult representing the result.</returns>
        public async Task<IActionResult> ToActionResultAsync(IErrorHttpMapper? errorMapper = null)
        {
            var result = await awaitableResult;
            return result.ToActionResult(errorMapper);
        }

        /// <summary>
        ///     Converts a non-generic Result to an IResult, allowing a DTO to be mapped on success.
        ///     On success, returns 200 OK with the mapped DTO. On failure, maps the error to an appropriate HTTP status code.
        /// </summary>
        /// <param name="dtoMapper">A function that maps the Result to a DTO on success.</param>
        /// <param name="errorMapper">Optional custom error mapper. If not provided, a default mapper is used.</param>
        /// <returns>An IResult representing the converted HTTP response.</returns>
        public async Task<IActionResult> ToActionResultAsync<TDto>(Func<TDto> dtoMapper,
            IErrorHttpMapper? errorMapper = null)
        {
            var result = await awaitableResult;
            return result.ToActionResult(dtoMapper, errorMapper);
        }

        /// <summary>
        ///     Converts a Result into an IActionResult for use in minimal API endpoints.
        ///     On success, it maps the result to a DTO using the provided mapping function and converts it into an IActionResult
        ///     using the success response mapper.
        ///     On failure, it utilizes an optional error mapper to map the error to an appropriate IActionResult.
        /// </summary>
        /// <typeparam name="TValue">The type of the value to map from the result.</typeparam>
        /// <param name="dtoMapper">A function that produces a DTO from the result when it is successful.</param>
        /// <param name="httpMapper">A function that converts the DTO to an IActionResult when the result is successful.</param>
        /// <param name="errorMapper">
        ///     An optional mapper for customizing the error-to-IActionResult mapping. If not provided, a
        ///     default mapping is used.
        /// </param>
        /// <returns>An IActionResult representing either the success or failure of the provided result.</returns>
        public async Task<IActionResult> ToActionResultAsync<TValue>(Func<TValue> dtoMapper,
            Func<TValue, IActionResult> httpMapper,
            IErrorHttpMapper? errorMapper = null)
        {
            var result = await awaitableResult;
            return result.ToActionResult(dtoMapper, httpMapper, errorMapper);
        }
    }

    /// <summary>
    /// Provides extension methods for efficiently converting <see cref="Task{TResult}" /> of
    /// <see cref="Result{TValue}" /> into HTTP-compatible results (<see cref="IActionResult" />)
    /// suitable for use in ASP.NET Core MVC controllers.
    /// </summary>
    extension<TValue>(Task<Result<TValue>> awaitableResult) where TValue : notnull
    {
        /// <summary>
        ///     Converts a Result&lt;T&gt; to a CreatedAtAction IActionResult for MVC controllers.
        ///     Success returns 201 Created with location and value, failure maps error to appropriate status code.
        /// </summary>
        /// <param name="actionName">Name of the action to link to.</param>
        /// <param name="routeValues">Route values for the action.</param>
        /// <param name="errorMapper">Optional custom error mapper. Uses default if not provided.</param>
        /// <returns>An IActionResult representing the result.</returns>
        public async Task<IActionResult> ToCreatedActionResultAsync(string actionName,
            object? routeValues = null,
            IErrorHttpMapper? errorMapper = null)
        {
            var result = await awaitableResult;
            return result.ToCreatedActionResult(actionName, routeValues, errorMapper);
        }

        /// <summary>
        ///     Converts a Result&lt;T&gt; to a CreatedAtAction IActionResult for MVC controllers with DTO mapping.
        ///     Success returns 201 Created with location and mapped DTO, failure maps error to appropriate status code.
        /// </summary>
        /// <typeparam name="TDto">The type of the DTO to map to.</typeparam>
        /// <param name="actionName">Name of the action to link to.</param>
        /// <param name="dtoMapper">Function to map the value to a DTO.</param>
        /// <param name="routeValues">Route values for the action.</param>
        /// <param name="errorMapper">Optional custom error mapper. Uses default if not provided.</param>
        /// <returns>An IActionResult representing the result.</returns>
        public async Task<IActionResult> ToCreatedActionResultAsync<TDto>(string actionName,
            Func<TValue, TDto> dtoMapper,
            object? routeValues = null,
            IErrorHttpMapper? errorMapper = null)
        {
            var result = await awaitableResult;
            return result.ToCreatedActionResult(actionName, dtoMapper, routeValues, errorMapper);

        }

        /// <summary>
        ///     Converts a Result&lt;T&gt; to an IResult for minimal API endpoints with DTO mapping.
        ///     Success returns 200 OK with mapped DTO, failure maps error to appropriate status code.
        /// </summary>
        /// <typeparam name="TDto">The type of the DTO to map to.</typeparam>
        /// <param name="dtoMapper">Function to map the value to a DTO.</param>
        /// <param name="errorMapper">Optional custom error mapper. Uses default if not provided.</param>
        /// <returns>An IResult representing the result.</returns>
        public async Task<IActionResult> ToActionResultAsync<TDto>(Func<TValue, TDto> dtoMapper,
            IErrorHttpMapper? errorMapper = null)
        {
            var result = await awaitableResult;
            return result.ToActionResult(dtoMapper, errorMapper);
        }

        /// <summary>
        ///     Converts a Result&lt;T&gt; to an IResult for minimal API endpoints.
        ///     Success returns 200 OK with value, failure maps error to appropriate status code.
        /// </summary>
        /// <param name="mapper">Optional custom error mapper. Uses default if not provided.</param>
        /// <returns>An IResult representing the result.</returns>
        public async Task<IActionResult> ToActionResultAsync(IErrorHttpMapper? mapper = null)
        {
            var result = await awaitableResult;
            return result.ToActionResult(mapper);
        }

        /// <summary>
        ///     Converts a <see cref="Result{TValue}" /> into an <see cref="IActionResult" /> for minimal API responses.
        ///     Maps the result's success value to an HTTP response using the provided DTO and HTTP mappers, or maps errors to HTTP
        ///     responses using an error mapper.
        /// </summary>
        /// <typeparam name="TDto">The type of the DTO produced from the result value.</typeparam>
        /// <param name="dtoMapper">A function to transform the result's value into a DTO.</param>
        /// <param name="httpMapper">A function to create an HTTP result from the result value and its mapped DTO.</param>
        /// <param name="errorMapper">
        ///     An optional mapper to handle errors and convert them into HTTP responses. Defaults to a
        ///     predefined implementation if not provided.
        /// </param>
        /// <returns>An <see cref="IActionResult" /> representing the HTTP response for the result.</returns>
        public async Task<IActionResult> ToActionResultAsync<TDto>(Func<TValue, TDto> dtoMapper,
            Func<TValue, TDto, IActionResult> httpMapper,
            IErrorHttpMapper? errorMapper = null)
        {
            var result = await awaitableResult;
            return result.ToActionResult(dtoMapper, httpMapper, errorMapper);
        }
    }
}